set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-yank'
# set -g @plugin 'catppuccin/tmux'

# set -g @catppuccin_flavor 'mocha'

run '~/.tmux/plugins/tpm/tpm'

set -g default-terminal "screen-256color"
set -g status-right "#[bg=colour135] 🐳[#(docker ps -q 2>/dev/null | wc -l | tr -d ' ')] | 🔐[#(veracrypt --text --list 2>/dev/null | wc -l | tr -d ' ')]"
set-option -g status-right-length 100

set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

set-option -g mouse on
set-option -g mode-keys vi

set -s copy-command 'pbcopy'
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel
bind -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel

bind '"' split-window -v -c "#{pane_current_path}"
bind v split-window -h -c "#{pane_current_path}"

bind r source-file ~/.tmux.conf \; display-message "tmux reloaded"

bind g display-popup \
  -d "#{pane_current_path}" \
  -w 80% \
  -h 80% \
  -E "lazygit"

# bind C-y display-popup \
#   -d "#{pane_current_path}" \
#   -w 80% \
#   -h 80% \
#   -E "YAZI_PASSTHROUGH=0 yazi"


unbind \'
bind \' display-popup \
  -d "#{pane_current_path}" \
  -w 75% \
  -h 60% \
  -E "zsh"

bind C-y display-popup -d '#{pane_current_path}' -h 80% -w 80% -E 'tmux new-session yazi \; set status off'
# bind C-y display-popup -d '#{pane_current_path}' -h 82% -w 80% -E 'tmux new-session -A -s yazi-popup -f /dev/null "yazi"; tmux kill-session -t yazi-popup'
# bind C-y new-window -c "#{pane_current_path}" -n "yazi" "yazi; tmux last-window"
