[[mgr.prepend_keymap]]
on = [ "m" ]
run = "plugin bookmarks save"
desc = "Save current position as a bookmark"

[[mgr.prepend_keymap]]
on = [ "'" ]
run = "plugin bookmarks jump"
desc = "Jump to a bookmark"

[[mgr.prepend_keymap]]
on = [ "b", "D" ]
run = "plugin bookmarks delete_all"
desc = "Delete all bookmarks"

[[mgr.prepend_keymap]]
on = [ "<", "s" ]
run = "linemode size"
desc = "Linemode: size"

[[mgr.prepend_keymap]]
on = [ "<", "p" ]
run = "linemode permissions"
desc = "Linemode: permissions"

[[mgr.prepend_keymap]]
on = [ "<", "b" ]
run = "linemode btime"
desc = "Linemode: btime"

[[mgr.prepend_keymap]]
on = [ "<", "m" ]
run = "linemode mtime"
desc = "Linemode: mtime"

[[mgr.prepend_keymap]]
on = [ "<", "o" ]
run = "linemode owner"
desc = "Linemode: owner"

[[mgr.prepend_keymap]]
on = [ "<", "n" ]
run = "linemode none"
desc = "Linemode: none"

